#!/bin/bash

# Simple scripts to monitor memory & cpu usage
MEMORY=$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')
CPU=$(top -bn1 | grep load | awk '{printf "%.2f%%\n", $(NF-2)}')
echo "▤ $MEMORY | ▥ $CPU"
