#!/bin/bash

# Launch rofi with custom configuration
rofi -sidebar-mode \
-modi run,drun,window,ssh \
-show drun \
-display-drun "Search " \
-display-ssh "SSH " \
-display-run "Run " \
-display-window "Workspace " \
-hide-scrollbar true \
-switchers "file:rofi-file-browser.sh" \
-show-icons \
-show file \
-columns 3 \
-font "Operator Mono Lig Book 12"

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
